### ISSUE TITLE
Migration from pure JSON to an actual DB

### ISSUE THREAD

**Issue by sivertschou** [sivertschou/dundring#196]
We should use an actual database, at least for handling user data.

Looking to implement a [Prisma powered database](https://www.prisma.io/), starting with `sqlite`.

Workouts might be fine as JSON – we'll look in to that down the line.

**Comment by sivertschou** [comment]
Solved by #213

**Comment by ruheni** [comment]
Hey 👋🏽

I'm glad to see that you chose Prisma for dundring. I've updated our Prisma Examples repo README listing dundring in the list ["Real-world & production-ready example projects using Prisma"](https://github.com/prisma/prisma-examples#real-world--production-ready-example-projects-with-prisma)

<img width="591" alt="Screenshot 2022-12-19 at 11 36 23" src="https://user-images.githubusercontent.com/33921841/208408033-1b4073c2-7d1d-41e3-9b14-c532bbbfdeb3.png">

**Comment by sivertschou** [comment]
Awesome! Thanks for listing us and thanks for the amazing software! 🤩 @ruheni
