### ISSUE TITLE
Plot GPS-coordinates

### ISSUE THREAD

**Issue by sivertschou** [sivertschou/dundring#20]
Plot GPS-coordinates over time.

Potentially, we should make it possible to plot different types of GPS paths/figures

![image](https://user-images.githubusercontent.com/31168035/139814136-b2e5b9df-e7d6-41c1-9895-9b351dd83114.png)

**Comment by morteako** [comment]
Closed?

**Comment by morteako** [comment]
closed?

**Comment by sivertschou** [comment]
Hehe, yepp! Solved by #140
