### ISSUE TITLE
add a License

### ISSUE THREAD

**Issue by dvmarinoff** [sivertschou/dundring#217]
Hey, folks, great work so far!

I've written some trainer control code in the past and I am seeing some places in the project where I can possibly contribute, but I can't find a license for the code. Do you have one?

**Comment by sivertschou** [comment]
Thank you for reaching out, and pardon the slow response time! We have been discussing this for the last days, and have created #218 which adds the Apache 2.0 license 🤠

**Comment by sivertschou** [comment]
#218 Solves this 🚀
