### ISSUE TITLE
Imported workout does not appear anywhere when saved

### ISSUE THREAD

**Issue by sondresl** [sivertschou/dundring#256]
Firstly, big fan of dundring, I use it a lot, great work ⚡ 🤠 🤡 

When I import a workout, i.e. by clicking link (e.g. https://dundring.com/workout/874e76bd-f829-459a-bf62-5edae4e2d79b) and
then save that workout, it does not appear anywhere in the list of workouts.

See the video of me replicating the bug here:

https://github.com/sivertschou/dundring/assets/23271245/07c3b48f-445b-4901-a3bf-79bc417771c7

There seems to either be something saved or cached between imports, because I changed the name of the workout before trying to save and that name is retained on repeated imports. I am also asked if I want to discard changes.

**Comment by morteako** [comment]
Great description!
We should look into this

**Comment by morteako** [comment]
Reproduced in prod.
Will try to reproduce locally

**Comment by morteako** [comment]
Cant seem to reproduce locally.

But this actually saves the changes in the original workout, from the sender???

![2023-10-22 23 26 51](https://github.com/sivertschou/dundring/assets/21218279/301e358c-c21a-40ee-957e-9891480d92ef)

This is pretty bad 🙃

**Comment by morteako** [comment]
I think this is closed by #261 
reopen if not :))
