### ISSUE TITLE
Change power control buttons to adjust absolute watt, not %

### ISSUE THREAD

**Issue by morteako** [sivertschou/dundring#257]
<img width="509" alt="image" src="https://github.com/sivertschou/dundring/assets/21218279/7126df5c-7083-449e-aed4-d5bcbe180a70">

Should just be +- 1W, 5W, 25W (or something like that. up for discussion) or something like that .
Not % based on the ftp as it is currently.
I think we kinda agreed that this is less confusing, if i remember correctly , @sivertschou ?

**Comment by sivertschou** [comment]
I agree! We discussed this and concluded that Watt values would feel mer intuitive 🤠
